### ISSUE TITLE
关于CNN部分的训练代码

### ISSUE THREAD

**Issue by ccnuJLiu** [zhuwenxing/Deep_Learning_Based_Power_Control#1]
您好！谢谢您的分享，我看到关于CNN部分的代码，有network部分的代码，我自己也尝试进行了这篇论文的复现，但是效果特别不好，功率分配输出的基本对于每个样本都是一模一样的输出，请问下您有做完剩余部分的训练代码吗？如果可以分享，不胜感激！也可以有偿分享，我尝试了很多次，始终没有论文的效果，希望能够得到您的帮助。

**Comment by zhuwenxing** [comment]
Hi，你可以到作者的 @seotaijiya自己的Github主页去找一下这篇文章的类似实现。个人认为这篇论文主要的贡献点是提出使用无（自）监督训练，CNN的网络结构倒不是什么重点，在一些[论文](https://arxiv.org/abs/1907.08487)中也提到基于CNN的网络结构较于MLP是结果会差一些。

**Comment by ccnuJLiu** [comment]
好的，相当感谢！
